### PR TITLE
feat: Update "app_vote" entry for english locale

### PR DESCRIPTION
**Pull request by gsouquet**
Hi,

Upon using Cozy I noticed this piece of copy that has been bugging me a bit. Opening a PR to update two minor things I have noticed

- Changed the structure of the sentence to tone it down a bit and make it bit more idiomatic
- Update "connection" spelling to its most common form

### CODE REVIEW

**Comment by Crash--** [comment]
Thanks @gsouquet ! What a day ! 2 issues and one PR.  Thanks !

Can you update the snapshots with yarn jest -u ?

**Comment by gsouquet** [comment]
> Thanks @gsouquet ! What a day ! 2 issues and one PR. Thanks !
> 
> Can you update the snapshots with yarn jest -u ?

Yes, lockdown got me bad 😂
Those are minor fixes or things I've noticed. That's the bare minimum I can do 💯 

I have updated the relevant snapshot. For the record there are two other files that generated a diff but they had nothing to do with that PR so I did not include them as part of this piece of work.

Thank you for updating my PR title to follow the semantic PR convention

**Comment by nono** [comment]
Ping @Crash--

**Comment by Crash--** [comment]
My bad, forgot about this one.

Thanks for the reminder @nono and thanks again @gsouquet :)

**Pull request merged**
