### PR TITLE
[SCR-683] feat: Add new categories to the store and their locales

### PR DESCRIPTION
**Pull request by KillianCourvoisier**
```
### ✨ Features

* Adds "clouds", "finance" and "tech" in known categories
* Adds new locales for each new categories

```

### CODE REVIEW

**Comment by cballevre** [comment]
Thanks for your PR but it will miss the part about cozy-ui. If you want to have section title you should add your translation here also : https://github.com/cozy/cozy-ui/blob/master/react/AppSections/locales/en.json pls 🙏

**Comment by KillianCourvoisier** [comment]
Sure, didn't noticed that 🙏

**Comment by KillianCourvoisier** [comment]
Hop @cballevre https://github.com/cozy/cozy-ui/pull/2663 here you are, can you do the review here et there if it all ok for you ?

**Review by cballevre — APPROVED** [review]
This PR looks good to me 👍 You just need to update cozy-ui with the new version before merge it

**Comment by cballevre** [comment]
@acezard are you aware of this new translation for the home ? Maybe should we add them

**Pull request merged**
