### PR TITLE
Add application vote

### PR DESCRIPTION
**Pull request by CPatchane**
screen shot 2018-06-13 at 14 00 57

### CODE REVIEW

**Comment by CPatchane** [comment]
[(1) [STO] ETU je peux voter pour les prochains connecteurs](https://trello.com/c/JUP2cWFL/1038-1-sto-etu-je-peux-voter-pour-les-prochains-connecteurs)

**Comment by gregorylegarec** [comment]
popup.js seems to be imported from Collect, isn't it ? What solution do we have to mutualize it ? Put it in cozy-client ?

**Comment by CPatchane** [comment]
Yes it is. I thought about it and I don't know where to put it :/. Maybe a cozy-libs global, this not related to cozy-client I think.

**Comment by CPatchane** [comment]
@gregorylegarec Now it uses the `PopupOpener` component from cozy-ui 👍

**Pull request merged**
